# Generated by Django 4.0.1 on 2022-01-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('recommendation', models.TextField()),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
