# Generated by Django 3.0.5 on 2020-05-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_id',
            field=models.IntegerField(default=2000, max_length=5),
            preserve_default=False,
        ),
    ]
