# Generated by Django 4.0.1 on 2022-01-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('institution', models.CharField(max_length=100)),
                ('survey_link', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'recipients',
            },
        ),
    ]
