# Generated by Django 3.0.7 on 2020-07-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytics',
        ),
        migrations.AddField(
            model_name='response',
            name='choice',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
