# Generated by Django 3.0.7 on 2020-07-05 02:35

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200704_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('responses', django_mysql.models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'analytics_vw',
                'managed': False,
            },
        ),
    ]
